Correction documentation VVV
WordCampParis/contribuer-a-wordpress pull request #27
Opened 2019-03-19 19:40 UTC by samy

- La commande de copie du .yml n'est plus nécessaire, elle est faite automatiquement par Vagrant
- L'utilisation du ~ pose problème sur des OS ne le gérant pas
- Les URLs comportent un * en trop à la fin

2019-03-19 21:37 UTC, imath requested changes
Hello, merci pour ta contribution 👍 Je suggère par souci de cohérence de ne plus utiliser `~` partout dans le document si c'est problématique.

2019-03-19 21:37 UTC, imath commented on logiciels/vvv.md
>  cd ~/vagrant-local
Du coup faudrait-il aussi remplacer le `~` par `.` ici aussi ?

2019-03-20 04:55 UTC, samy commented on logiciels/vvv.md
>  cd ~/vagrant-local
Oui mille excuses, il s'agit d'un oubli :)

2019-03-20 05:09 UTC, samy reviewed
C'est uniformisé :)

2019-03-20 06:17 UTC, audrasjb commented
Bien vu et merci @samy !

2019-03-20 08:22 UTC, imath approved these changes

2019-03-20 08:22 UTC, merged